apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adrenlinerush-wiki-pvc
  namespace: adrenlinerush-wiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: local-path 
